version = "1.0"

[metadata]
name = "arm7-triage"
author_name = "Nick Moore"
author_email = "nick.moore@pm.me"
category = "build-and-dependency-management"
difficulty = "medium"
tags = ["debugging", "cross-compilation", "rust", "arm", "qemu"]

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[environment]
type = "docker"
build_timeout_sec = 600.0
cpus = 1
memory_mb = 4096
storage_mb = 10240
