[target.armv7-unknown-linux-musleabihf]
linker = "/usr/bin/arm-linux-musleabihf-gcc"
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-static",
  "-C", "link-arg=-no-pie"
]

[target.armv7-unknown-linux-gnueabihf]
linker = "/usr/bin/arm-linux-gnueabihf-gcc"

[env]
CC_armv7_unknown_linux_musleabihf = "/usr/bin/arm-linux-musleabihf-gcc"
CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER = "/usr/bin/arm-linux-musleabihf-gcc"
CC_armv7_unknown_linux_gnueabihf = "/usr/bin/arm-linux-gnueabihf-gcc"
CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER = "/usr/bin/arm-linux-gnueabihf-gcc"
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_SYSROOT_DIR = "/usr/arm-linux-gnueabihf"
PKG_CONFIG_LIBDIR = "/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig"
